[package]
name = "rmenu"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xcb = "0.9.0"
pangocairo = "0.14.0"

[dependencies.cairo-rs]
version = "0.14.1"
features = [ "xcb" ]
